"""
OpenAPI to MCP Server Generator - Streamlit UI (Fixed)

Fixes applied:
- Output directory is now written INSIDE the tempfile.TemporaryDirectory() context,
  then the ZIP is read into memory before the context exits — eliminates the race
  condition where two concurrent users with the same server name corrupted each other
- requirements.txt generated for the MCP server now pins fastmcp>=2.0 (was 0.2.0
  which has an incompatible API for app.run())
- ZIP bytes are buffered in memory so the download button works even after tmpdir cleanup
"""

import streamlit as st
import shutil
import tempfile
import io
from pathlib import Path
import re
import zipfile
import traceback
import sys
from typing import List

from generator.openapi_loader import load_openapi_spec, OpenAPILoadError
from generator.tool_ir_builder import build_tool_ir
from generator.executor_mapper import generate_executor_file
from generator.python_sdk_codegen import generate_mcp_server

# ====================================================
# Constants
# ====================================================
MAX_ZIP_SIZE_MB = 20
MAX_FILES_IN_ZIP = 100
MAX_FILE_SIZE_MB = 50
ALLOWED_EXTENSIONS = {".yaml", ".yml", ".json"}

# ====================================================
# Page Configuration
# ====================================================
st.set_page_config(
    page_title="OpenAPI → MCP Server Generator",
    page_icon="⚙️",
    layout="centered",
    initial_sidebar_state="collapsed"
)

st.title("⚙️ OpenAPI → MCP Server Generator")
st.markdown("Convert any OpenAPI specification into a working FastMCP server")
st.markdown("---")

# ====================================================
# Helper Functions
# ====================================================

def sanitize_server_name(name: str) -> str:
    """Sanitize server name to be filesystem and Python-safe."""
    name = name.strip().lower()
    name = re.sub(r"\s+", "_", name)
    name = re.sub(r"[^a-z0-9_-]", "", name)
    return name or "mcp_server"


def secure_extract_zip(zip_path: Path, extract_dir: Path) -> List[Path]:
    """
    Safely extract ZIP with security checks.
    Returns list of extracted file paths.
    """
    extracted_files = []

    with zipfile.ZipFile(zip_path, "r") as z:
        if len(z.infolist()) > MAX_FILES_IN_ZIP:
            raise RuntimeError(f"ZIP contains too many files (max {MAX_FILES_IN_ZIP})")

        for info in z.infolist():
            if info.file_size > MAX_FILE_SIZE_MB * 1024 * 1024:
                raise RuntimeError(f"File too large in ZIP: {info.filename}")

            if Path(info.filename).is_absolute():
                raise RuntimeError("ZIP contains absolute paths")

            resolved_path = (extract_dir / info.filename).resolve()
            if not str(resolved_path).startswith(str(extract_dir.resolve())):
                raise RuntimeError("ZIP path traversal detected")

            if info.is_dir():
                continue

            if resolved_path.suffix.lower() not in ALLOWED_EXTENSIONS:
                continue

            resolved_path.parent.mkdir(parents=True, exist_ok=True)
            with z.open(info) as src, open(resolved_path, "wb") as dst:
                shutil.copyfileobj(src, dst)

            extracted_files.append(resolved_path)

    return extracted_files


def generate_requirements_txt(output_dir: Path) -> None:
    """
    Generate requirements.txt for the MCP server.
    Fix: fastmcp pinned to >=2.0 — version 0.2.0 had an incompatible app.run() API.
    """
    requirements = [
        "# FastMCP Server Dependencies",
        "# Generated by OpenAPI to MCP Generator",
        "",
        "# Core dependencies",
        "fastmcp>=2.0",          # Fix: was fastmcp==0.2.0 — incompatible API
        "httpx>=0.27.0",
        "python-dotenv>=1.0.1",
        "pydantic>=2.0",
        "",
        "# For OpenAPI spec loading",
        "pyyaml>=6.0",
        "",
        "# Optional: Enhanced validation",
        "jsonschema>=4.21.0",
    ]

    requirements_file = output_dir / "requirements.txt"
    with open(requirements_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(requirements))


# ====================================================
# UI: File Upload
# ====================================================
st.subheader("Step 1: Upload OpenAPI Specification")

uploaded_files = st.file_uploader(
    "Upload OpenAPI file(s)",
    type=["yaml", "yml", "json", "zip"],
    accept_multiple_files=True,
    help="Supports YAML, JSON, or ZIP archives containing multiple specs"
)

st.text("")

# ====================================================
# UI: Server Name Input
# ====================================================
st.subheader("Step 2: Server Name")

server_name_input = st.text_input(
    "Enter a name for your MCP server",
    placeholder="e.g. stripe-api-server",
    help="Alphanumeric characters, hyphens, and underscores only"
)

st.text("")

# ====================================================
# UI: Generate Button
# ====================================================
col1, col2, col3 = st.columns([2, 1, 1])

with col1:
    generate_button = st.button(
        "🔨 Generate Server", type="primary", use_container_width=True
    )

# ====================================================
# Generation Logic
# ====================================================
if generate_button:
    if not uploaded_files:
        st.error("❌ Please upload at least one OpenAPI file")
        st.stop()

    if not server_name_input:
        st.warning("⚠️ Please enter a server name")
        st.stop()

    server_name = sanitize_server_name(server_name_input)
    if not server_name:
        st.error("❌ Invalid server name")
        st.stop()

    st.divider()
    st.subheader(f"Generating: `{server_name}`")

    try:
        progress_bar = st.progress(0)
        status_text = st.empty()

        all_tools = []
        processed_files = 0
        total_files = len(uploaded_files)

        # Fix: all file I/O — including output generation and ZIP creation —
        # happens INSIDE the with block. The ZIP bytes are read into memory
        # before the block exits so the download button still works afterward.
        zip_bytes: bytes = b""

        with tempfile.TemporaryDirectory() as workdir:
            workdir_path = Path(workdir)

            # --------------------------------------------------
            # Process uploaded files
            # --------------------------------------------------
            for uploaded_file in uploaded_files:
                filename = uploaded_file.name
                suffix = Path(filename).suffix.lower()

                processed_files += 1
                progress = int((processed_files / (total_files + 4)) * 100)
                progress_bar.progress(progress)
                status_text.text(f"Processing: {filename}...")

                try:
                    if suffix == ".zip":
                        if uploaded_file.size > MAX_ZIP_SIZE_MB * 1024 * 1024:
                            raise RuntimeError(
                                f"ZIP file exceeds {MAX_ZIP_SIZE_MB}MB limit"
                            )

                        zip_path = workdir_path / filename
                        zip_path.write_bytes(uploaded_file.read())

                        extract_dir = workdir_path / zip_path.stem
                        extract_dir.mkdir(parents=True, exist_ok=True)

                        extracted_specs = secure_extract_zip(zip_path, extract_dir)

                        if not extracted_specs:
                            st.warning(f"⚠️ No OpenAPI files found in {filename}")
                            continue

                        for spec_file in extracted_specs:
                            namespace = spec_file.stem.lower()
                            try:
                                openapi = load_openapi_spec(spec_file)
                                tools = build_tool_ir(openapi, namespace=namespace)
                                all_tools.extend(tools)
                                st.success(
                                    f"✓ Loaded {len(tools)} tools from {spec_file.name}"
                                )
                            except OpenAPILoadError as e:
                                st.error(f"❌ Error loading {spec_file.name}: {e}")
                                continue

                    else:
                        temp_path = workdir_path / filename
                        temp_path.write_bytes(uploaded_file.read())

                        try:
                            openapi = load_openapi_spec(temp_path)
                            namespace = temp_path.stem.lower()
                            tools = build_tool_ir(openapi, namespace=namespace)
                            all_tools.extend(tools)
                            st.success(f"✓ Loaded {len(tools)} tools from {filename}")
                        except OpenAPILoadError as e:
                            st.error(f"❌ Error loading {filename}: {e}")
                            continue

                except Exception as e:
                    st.error(f"❌ Error processing {filename}: {e}")
                    continue

            if not all_tools:
                raise RuntimeError("No tools generated from the uploaded files")

            progress_bar.progress(70)
            status_text.text("Generating executors...")

            # --------------------------------------------------
            # Generate output — inside tmpdir to avoid cross-user races
            # --------------------------------------------------
            server_output_dir = workdir_path / "output" / server_name
            server_output_dir.mkdir(parents=True, exist_ok=True)

            generate_executor_file(all_tools, str(server_output_dir / "executors.py"))

            progress_bar.progress(80)
            status_text.text("Generating server.py...")

            generate_mcp_server(all_tools, server_output_dir, server_name=server_name)

            progress_bar.progress(88)
            status_text.text("Generating dependencies...")

            generate_requirements_txt(server_output_dir)

            progress_bar.progress(95)
            status_text.text("Packaging...")

            # Create ZIP archive inside tmpdir
            zip_base = workdir_path / server_name
            zip_path_str = shutil.make_archive(
                base_name=str(zip_base),
                format="zip",
                root_dir=str(server_output_dir)
            )

            # Fix: read ZIP into memory NOW, before tmpdir is deleted
            with open(zip_path_str, "rb") as zf:
                zip_bytes = zf.read()

        # tmpdir is now cleaned up — zip_bytes is safely in memory
        progress_bar.progress(100)
        status_text.text("✅ Complete!")

        st.divider()

        # ====================================================
        # Download Button
        # ====================================================
        st.download_button(
            label=f"⬇️ Download Server ({server_name}.zip)",
            data=zip_bytes,
            file_name=f"{server_name}.zip",
            mime="application/zip",
            use_container_width=True
        )

        st.text("")

        # ====================================================
        # Summary Statistics
        # ====================================================
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Total Tools", len(all_tools))
        with col2:
            namespaces = len(set(t.get('namespace', 'default') for t in all_tools))
            st.metric("Namespaces", namespaces)
        with col3:
            has_files = sum(
                1 for t in all_tools
                if t.get('request_body', {}).get('supports_files')
            )
            st.metric("File Upload Tools", has_files)

        st.text("")

        # ====================================================
        # Generated Tools Display
        # ====================================================
        with st.expander("📊 View All Generated Tools"):
            tools_by_namespace: dict = {}
            for tool in all_tools:
                ns = tool.get('namespace') or 'default'
                if ns not in tools_by_namespace:
                    tools_by_namespace[ns] = []
                tools_by_namespace[ns].append(tool)

            for ns in sorted(tools_by_namespace.keys()):
                ns_tools = tools_by_namespace[ns]
                st.markdown(f"### {ns.upper()} ({len(ns_tools)} tools)")

                for tool in ns_tools[:10]:
                    with st.container():
                        c1, c2, c3 = st.columns([1, 1, 2])
                        with c1:
                            st.code(tool['method'], language="text")
                        with c2:
                            st.code(tool['path'], language="text")
                        with c3:
                            st.caption(tool.get('description', 'No description'))

                if len(ns_tools) > 10:
                    st.info(f"... and {len(ns_tools) - 10} more tools")

        st.divider()

        # ====================================================
        # Setup Instructions
        # ====================================================
        with st.expander("📖 Setup Instructions", expanded=True):
            st.markdown(f"""
**1. Extract the downloaded ZIP:**
```bash
unzip {server_name}.zip -d {server_name}
cd {server_name}
```

**2. Install dependencies:**
```bash
pip install -r requirements.txt
```

**3. Configure environment:**
```bash
nano .env
# Set your API URL (REQUIRED)
MCP_API_BASE_URL=https://your-api-url.com
# Set authentication (if needed)
MCP_AUTH_HEADER=Authorization
MCP_AUTH_SCHEME=Bearer
MCP_AUTH_TOKEN=your-token-here
```

**4. Run the server:**
```bash
python server.py
```

**5. Connect with Claude Desktop:**

Add to `~/Library/Application Support/Claude/claude_desktop_config.json` (macOS):
```json
{{
  "mcpServers": {{
    "{server_name}": {{
      "command": "python",
      "args": ["/absolute/path/to/{server_name}/server.py"]
    }}
  }}
}}
```
On Windows: `%APPDATA%\\Claude\\claude_desktop_config.json`
            """)

    except Exception as e:
        st.error(f"❌ Generation failed: {str(e)}")
        with st.expander("🔍 Error Details"):
            st.code(traceback.format_exc())

# ====================================================
# Footer
# ====================================================
st.divider()
st.markdown("""
**OpenAPI → MCP Server Generator** | v2.4 Fixed
- ✅ Full OpenAPI 3.x support (3.0 and 3.1)
- ✅ Automatic validation & error handling
- ✅ File upload support
- ✅ Response schema metadata
- ✅ Per-API configuration via .env
- ✅ Python 3.9+ compatible
- ✅ Production-ready code generation
""")